android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "com.neelkanth.accountbook"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        
        // Forced Higher Version Code to bypass downgrade conflicts
        versionCode 1005
        versionName "1.0.5"
    }

    buildTypes {
        debug {
            // Force debug build to use static release debug keys
            matchingFallbacks = ['release']
        }
    }
}
